# Generated by Django 2.1.7 on 2020-03-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_manager',
            field=models.BooleanField(default=False, verbose_name='user manager status'),
        ),
    ]
