# Generated by Django 2.2.8 on 2020-03-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_user_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_unhashed',
        ),
    ]
