# Generated by Django 2.2.8 on 2020-03-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings',
            new_name='Setting',
        ),
    ]
