# Generated by Django 2.2.8 on 2020-03-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workingDays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='workingDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayNotes', to='workingDays.WorkingDay'),
        ),
    ]
