# Generated by Django 2.2.8 on 2020-03-17 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workingDays', '0002_auto_20200317_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingday',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together={('owner', 'date')},
        ),
    ]
