# Generated by Django 2.2.8 on 2020-03-10 16:41

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200306_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='end',
        ),
        migrations.RemoveField(
            model_name='note',
            name='start',
        ),
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='note',
            name='hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
