# Generated by Django 2.2.8 on 2020-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200310_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='underPWH',
            field=models.BooleanField(default=False, verbose_name='Under Preferred Working Hours ?'),
        ),
    ]
